from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch


def generate_report(
    filename,
    username,
    skills,
    missing_skills,
    careers,
    score
):

    pdf = canvas.Canvas(
        filename,
        pagesize=A4
    )

    width, height = A4

    y = height - 50

    pdf.setFont(
        "Helvetica-Bold",
        20
    )

    pdf.drawString(
        50,
        y,
        "SkillSphere AI"
    )

    y -= 35

    pdf.setFont(
        "Helvetica",
        12
    )

    pdf.drawString(
        50,
        y,
        f"User: {username}"
    )

    y -= 30

    pdf.setFont(
        "Helvetica-Bold",
        14
    )

    pdf.drawString(
        50,
        y,
        "Resume Analysis Report"
    )

    y -= 30

    # Detected Skills

    pdf.setFont(
        "Helvetica-Bold",
        12
    )

    pdf.drawString(
        50,
        y,
        "Detected Skills:"
    )

    y -= 20

    pdf.setFont(
        "Helvetica",
        11
    )

    for skill in skills:

        pdf.drawString(
            70,
            y,
            f"- {skill}"
        )

        y -= 18

    y -= 10

    # Missing Skills

    pdf.setFont(
        "Helvetica-Bold",
        12
    )

    pdf.drawString(
        50,
        y,
        "Missing Skills:"
    )

    y -= 20

    pdf.setFont(
        "Helvetica",
        11
    )

    if missing_skills:

        for skill in missing_skills:

            pdf.drawString(
                70,
                y,
                f"- {skill}"
            )

            y -= 18

    else:

        pdf.drawString(
            70,
            y,
            "No Missing Skills"
        )

        y -= 18

    y -= 10

    # Career Recommendations

    pdf.setFont(
        "Helvetica-Bold",
        12
    )

    pdf.drawString(
        50,
        y,
        "Career Recommendations:"
    )

    y -= 20

    pdf.setFont(
        "Helvetica",
        11
    )

    for career in careers:

        pdf.drawString(
            70,
            y,
            f"- {career}"
        )

        y -= 18

    y -= 10

    # Resume Score

    pdf.setFont(
        "Helvetica-Bold",
        12
    )

    pdf.drawString(
        50,
        y,
        f"Resume Score: {score}/100"
    )

    y -= 30

    pdf.setFont(
        "Helvetica",
        10
    )

    pdf.drawString(
        50,
        y,
        "Generated by SkillSphere AI"
    )

    pdf.save()

    return filename